### ISSUE TITLE
Encode/decode binárních dat

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/php-encryption#2]
Syrup si tuhle třídu obaluje a výstup encoduje do base64 (asi aby to mohl líp uložit do db?) viz. https://github.com/keboola/syrup-component-bundle/blob/master/Encryption/Encryptor.php Dávalo by smysl tu konverzi přidat přímo sem?

**Comment by Halama** [comment]
Prislo mi to tam zbytecny, do db to ukladam primo binarne. Proc to syrup obaluje nevim.

**Comment by JakubMatejka** [comment]
Ok, pozeptám se tam. ;o)
